# Generated by Django 6.0.2 on 2026-06-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CAPITAL', 'Business Capital'), ('SALE', 'Sales Revenue'), ('PURCHASE', 'Inventory Purchase'), ('EXPENSE', 'Business Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Notes about this transaction')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
