# Generated by Django 6.0.2 on 2026-06-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
