# Generated by Django 6.0.2 on 2026-06-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_purchasebatch_selling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
